- name: Create a jenkins job by using the token
  community.general.jenkins_job:
    config: "{{ lookup('template', '/tmp/pipeline.xml') }}"
    name: test
    url: http://172.31.4.194:8080
    user: "admin"
    token: "11edc4b20bcb8999dbaaecd36780af73cf"
  loop:
      - { repoName: "cart", componentName: "cart" }