- name: Create pipeline jobs
  community.general.jenkins_job:
    config: "{{ lookup('template', '/tmp/pipeline.xml') }}"
    name: "{{item.folderName}}{{item.jobName}}"
    url: http://172.31.4.194:8080
    user: "admin"
    token: "11edc4b20bcb8999dbaaecd36780af73cf"
  loop:
      - { jobName: "cart", folderName: "", repoName: "cart", componentName: "cart" }