- name: Create a jenkins job by using the token
  community.general.jenkins_job:
    config: "{{ lookup('template', 'templates/pipeline.xml') }}"
    name: test
    url: http://172.31.4.194:8080
    user: admin
    password: admin123
  loop:
    - {repoName: "cart", componentName: "cart"}